/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "pretenderdb"
include("pretender", "database-utils", "pretender-integ")

// Extract version from Git tag or use gradle.properties default
gradle.beforeProject {
    val gitVersion = providers.exec {
        commandLine("git", "describe", "--tags", "--exact-match", "HEAD")
        isIgnoreExitValue = true
    }.standardOutput.asText.get().trim()

    if (gitVersion.isNotEmpty() && gitVersion.startsWith("v")) {
        // Remove 'v' prefix from tag (v1.0.0 -> 1.0.0)
        // Validate semantic versioning format
        val versionPattern = Regex("^v(\\d+\\.\\d+\\.\\d+(-[a-zA-Z0-9.]+)?)$")
        val matchResult = versionPattern.matchEntire(gitVersion)
        if (matchResult != null) {
            version = matchResult.groupValues[1]
            logger.lifecycle("Using version from Git tag: $version")
        } else {
            logger.warn("Git tag '$gitVersion' does not match semantic versioning format (vX.Y.Z)")
        }
    }
}
